# Generated by Django 5.2 on 2026-02-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_post_tags_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
